import { useState } from "react";

export interface ReviewHunkView { id: string; path: string; before: string; after: string; eventSeq?: number; decision?: "accepted" | "rejected"; feedback?: string; }
export interface ReviewPanelProps { hunks: readonly ReviewHunkView[]; onDecision: (hunk: ReviewHunkView, decision: "accepted" | "rejected", feedback?: string) => void; onAcceptAll: () => void; onSeek: (seq: number) => void; }
export function ReviewPanel({ hunks, onDecision, onAcceptAll, onSeek }: ReviewPanelProps) {
  const [feedback, setFeedback] = useState<Record<string, string>>({});
  const pending = hunks.filter((hunk) => hunk.decision === undefined);
  return <section aria-label="Review changes" className="settings-panel review-panel"><div className="review-heading"><h2>Review changes</h2><button disabled={pending.length === 0} onClick={onAcceptAll}>Accept all</button></div>{hunks.map((hunk) => <article key={hunk.id} className="review-hunk"><button className="review-path" onClick={() => hunk.eventSeq === undefined ? undefined : onSeek(hunk.eventSeq)}><strong>{hunk.path}</strong>{hunk.eventSeq === undefined ? null : <small>event {hunk.eventSeq}</small>}</button><pre>{`- ${hunk.before}\n+ ${hunk.after}`}</pre><textarea aria-label={`Feedback for ${hunk.path}`} value={feedback[hunk.id] ?? hunk.feedback ?? ""} onChange={(event) => setFeedback((current) => ({ ...current, [hunk.id]: event.target.value }))} placeholder="Optional feedback" disabled={hunk.decision !== undefined} /><div className="review-actions"><button disabled={hunk.decision !== undefined} onClick={() => onDecision(hunk, "accepted", feedback[hunk.id])}>Accept</button><button disabled={hunk.decision !== undefined} onClick={() => onDecision(hunk, "rejected", feedback[hunk.id])}>Reject</button><span>{hunk.decision ?? "pending"}</span></div></article>)}</section>;
}
