import { describe, expect, it } from "vitest";
import { ControlLease, isAcceptedNotification, isUnauthorized, McpController, type McpOutcome } from "../src/server.js";

const handlers = { open_file: async ({ path }: { path: string }) => path, edit_file: async ({ path }: { path: string }) => path, save_file: async ({ path }: { path: string }) => path, run_command: async ({ command }: { command: string }) => command, animate_step: async ({ label }: { label: string }) => label };
const controller = new McpController({ token: "secret", handlers });
const request = (method: string, params?: Record<string, unknown>) => ({ jsonrpc: "2.0" as const, id: 1, method, ...(params === undefined ? {} : { params }) });
const notification = (method: string) => ({ jsonrpc: "2.0" as const, method });
const asResponse = (outcome: McpOutcome) => { if (isAcceptedNotification(outcome)) throw new Error("expected a response, not an accepted notification"); return outcome; };

describe("MCP server", () => {
  it("REQ-MPS-002 and REQ-MPS-003: authenticates and lists complete platform tools", async () => { const rejected = await controller.handle(request("tools/list"), "Bearer wrong", "client"); expect(asResponse(rejected).error?.code).toBe(-32001); expect(isUnauthorized(rejected)).toBe(true); const response = await controller.handle(request("tools/list"), "Bearer secret", "client"); expect((asResponse(response).result as { tools: Array<{ name: string }> }).tools.map((tool) => tool.name)).toEqual(["open_file", "edit_file", "save_file", "run_command", "animate_step"]); });
  it("REQ-MPS-003 and REQ-MPS-005: rejects invalid input and routes a valid call", async () => { expect(asResponse(await controller.handle(request("tools/call", { name: "edit_file", arguments: {} }), "Bearer secret", "client")).error?.code).toBe(-32602); const response = await controller.handle(request("tools/call", { name: "animate_step", arguments: { label: "visible" } }), "Bearer secret", "client"); expect(asResponse(response).result).toBeDefined(); });
  it("REQ-MPS-001: accepts id-less notifications without answering them", async () => { for (const method of ["notifications/initialized", "notifications/cancelled", "notifications/progress"]) expect(isAcceptedNotification(await controller.handle(notification(method), "Bearer secret", "client"))).toBe(true); expect(isUnauthorized(await controller.handle(notification("notifications/initialized"), "Bearer wrong", "client"))).toBe(true); });
  it("REQ-MPS-001: answers a malformed message with a null id so it cannot collide with a live request", async () => { const response = asResponse(await controller.handle({ jsonrpc: "1.0", id: "x" }, "Bearer secret", "client")); expect(response.id).toBeNull(); expect(response.error?.code).toBe(-32600); });
  it("REQ-MPS-005: reports a busy workspace while another owner holds mutation control", async () => { const lease = new ControlLease(); const serialized = new McpController({ token: "secret", handlers, lease }); expect(lease.acquire("internal-run")).toBe(true); const busy = asResponse(await serialized.handle(request("tools/call", { name: "animate_step", arguments: { label: "blocked" } }), "Bearer secret", "external")); expect(busy.error?.code).toBe(-32002); lease.release("internal-run"); expect(asResponse(await serialized.handle(request("tools/call", { name: "animate_step", arguments: { label: "allowed" } }), "Bearer secret", "external")).result).toBeDefined(); });
});
